version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    environment:
      - HOST=0.0.0.0
      - PORT=7777

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:7777
    volumes:
      - ./frontend:/app
      - /app/node_modules
